package org.qhn.coexist.shirojwtqhn.domain.entity;

import java.io.Serializable;
import java.util.Date;

public class QhnRoleFunctionDO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qhn_role_function.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qhn_role_function.role_id
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qhn_role_function.function_id
     *
     * @mbggenerated
     */
    private Long functionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qhn_role_function.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qhn_role_function.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qhn_role_function
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qhn_role_function.id
     *
     * @return the value of qhn_role_function.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qhn_role_function.id
     *
     * @param id the value for qhn_role_function.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qhn_role_function.role_id
     *
     * @return the value of qhn_role_function.role_id
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qhn_role_function.role_id
     *
     * @param roleId the value for qhn_role_function.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qhn_role_function.function_id
     *
     * @return the value of qhn_role_function.function_id
     *
     * @mbggenerated
     */
    public Long getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qhn_role_function.function_id
     *
     * @param functionId the value for qhn_role_function.function_id
     *
     * @mbggenerated
     */
    public void setFunctionId(Long functionId) {
        this.functionId = functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qhn_role_function.create_time
     *
     * @return the value of qhn_role_function.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qhn_role_function.create_time
     *
     * @param createTime the value for qhn_role_function.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qhn_role_function.update_time
     *
     * @return the value of qhn_role_function.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qhn_role_function.update_time
     *
     * @param updateTime the value for qhn_role_function.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_role_function
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleId=").append(roleId);
        sb.append(", functionId=").append(functionId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}