package org.qhn.coexist.shirojwtqhn.domain.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.qhn.coexist.shirojwtqhn.domain.entity.QhnFunctionDO;
import org.qhn.coexist.shirojwtqhn.domain.entity.QhnFunctionDOCriteria;

public interface QhnFunctionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_function
     *
     * @mbggenerated
     */
    int countByExample(QhnFunctionDOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_function
     *
     * @mbggenerated
     */
    int deleteByExample(QhnFunctionDOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_function
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_function
     *
     * @mbggenerated
     */
    int insert(QhnFunctionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_function
     *
     * @mbggenerated
     */
    int insertSelective(QhnFunctionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_function
     *
     * @mbggenerated
     */
    List<QhnFunctionDO> selectByExampleWithRowbounds(QhnFunctionDOCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_function
     *
     * @mbggenerated
     */
    List<QhnFunctionDO> selectByExample(QhnFunctionDOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_function
     *
     * @mbggenerated
     */
    QhnFunctionDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_function
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") QhnFunctionDO record, @Param("example") QhnFunctionDOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_function
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") QhnFunctionDO record, @Param("example") QhnFunctionDOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_function
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QhnFunctionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_function
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QhnFunctionDO record);
}