package org.qhn.coexist.shirojwtqhn.domain.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.qhn.coexist.shirojwtqhn.domain.entity.QhnRoleDO;
import org.qhn.coexist.shirojwtqhn.domain.entity.QhnRoleDOCriteria;

public interface QhnRoleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_role
     *
     * @mbggenerated
     */
    int countByExample(QhnRoleDOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_role
     *
     * @mbggenerated
     */
    int deleteByExample(QhnRoleDOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_role
     *
     * @mbggenerated
     */
    int insert(QhnRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_role
     *
     * @mbggenerated
     */
    int insertSelective(QhnRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_role
     *
     * @mbggenerated
     */
    List<QhnRoleDO> selectByExampleWithRowbounds(QhnRoleDOCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_role
     *
     * @mbggenerated
     */
    List<QhnRoleDO> selectByExample(QhnRoleDOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_role
     *
     * @mbggenerated
     */
    QhnRoleDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") QhnRoleDO record, @Param("example") QhnRoleDOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") QhnRoleDO record, @Param("example") QhnRoleDOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QhnRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QhnRoleDO record);
}