package org.qhn.coexist.shirojwtqhn.domain.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.qhn.coexist.shirojwtqhn.domain.entity.QhnRoleFunctionDO;
import org.qhn.coexist.shirojwtqhn.domain.entity.QhnRoleFunctionDOCriteria;

public interface QhnRoleFunctionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_role_function
     *
     * @mbggenerated
     */
    int countByExample(QhnRoleFunctionDOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_role_function
     *
     * @mbggenerated
     */
    int deleteByExample(QhnRoleFunctionDOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_role_function
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_role_function
     *
     * @mbggenerated
     */
    int insert(QhnRoleFunctionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_role_function
     *
     * @mbggenerated
     */
    int insertSelective(QhnRoleFunctionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_role_function
     *
     * @mbggenerated
     */
    List<QhnRoleFunctionDO> selectByExampleWithRowbounds(QhnRoleFunctionDOCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_role_function
     *
     * @mbggenerated
     */
    List<QhnRoleFunctionDO> selectByExample(QhnRoleFunctionDOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_role_function
     *
     * @mbggenerated
     */
    QhnRoleFunctionDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_role_function
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") QhnRoleFunctionDO record, @Param("example") QhnRoleFunctionDOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_role_function
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") QhnRoleFunctionDO record, @Param("example") QhnRoleFunctionDOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_role_function
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QhnRoleFunctionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_role_function
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QhnRoleFunctionDO record);
}