package org.qhn.coexist.shirojwtqhn.domain.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.qhn.coexist.shirojwtqhn.domain.entity.QhnUserRoleDO;
import org.qhn.coexist.shirojwtqhn.domain.entity.QhnUserRoleDOCriteria;

public interface QhnUserRoleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_user_role
     *
     * @mbggenerated
     */
    int countByExample(QhnUserRoleDOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_user_role
     *
     * @mbggenerated
     */
    int deleteByExample(QhnUserRoleDOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_user_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_user_role
     *
     * @mbggenerated
     */
    int insert(QhnUserRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_user_role
     *
     * @mbggenerated
     */
    int insertSelective(QhnUserRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_user_role
     *
     * @mbggenerated
     */
    List<QhnUserRoleDO> selectByExampleWithRowbounds(QhnUserRoleDOCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_user_role
     *
     * @mbggenerated
     */
    List<QhnUserRoleDO> selectByExample(QhnUserRoleDOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_user_role
     *
     * @mbggenerated
     */
    QhnUserRoleDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_user_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") QhnUserRoleDO record, @Param("example") QhnUserRoleDOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_user_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") QhnUserRoleDO record, @Param("example") QhnUserRoleDOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QhnUserRoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QhnUserRoleDO record);
}