package org.qhn.coexist.shirojwtqhn.domain.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.qhn.coexist.shirojwtqhn.domain.entity.QhnUserDO;
import org.qhn.coexist.shirojwtqhn.domain.entity.QhnUserDOCriteria;

public interface QhnUserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_user
     *
     * @mbggenerated
     */
    int countByExample(QhnUserDOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_user
     *
     * @mbggenerated
     */
    int deleteByExample(QhnUserDOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_user
     *
     * @mbggenerated
     */
    int insert(QhnUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_user
     *
     * @mbggenerated
     */
    int insertSelective(QhnUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_user
     *
     * @mbggenerated
     */
    List<QhnUserDO> selectByExampleWithRowbounds(QhnUserDOCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_user
     *
     * @mbggenerated
     */
    List<QhnUserDO> selectByExample(QhnUserDOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_user
     *
     * @mbggenerated
     */
    QhnUserDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") QhnUserDO record, @Param("example") QhnUserDOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") QhnUserDO record, @Param("example") QhnUserDOCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QhnUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qhn_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QhnUserDO record);
}